/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Sara
 */
public class PanelForma extends javax.swing.JPanel {

    /**
     * Creates new form PanelForma
     */
    public PanelForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eTuberculoCF = new javax.swing.JLabel();
        cajaFormaCF = new javax.swing.JTextField();
        eLabelCF = new javax.swing.JLabel();
        jComboBoxPapasCF = new javax.swing.JComboBox<>();
        btnConsultarF = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eTuberculoCF.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        eTuberculoCF.setText("Forma del Tubérculo");
        add(eTuberculoCF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 170, 20));

        cajaFormaCF.setBackground(new java.awt.Color(204, 255, 255));
        add(cajaFormaCF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 230, -1));

        eLabelCF.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        eLabelCF.setText("Papas");
        add(eLabelCF, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, -1, -1));

        jComboBoxPapasCF.setBackground(new java.awt.Color(204, 255, 255));
        jComboBoxPapasCF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBoxPapasCF, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 220, -1));

        btnConsultarF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/consultarPForma.jpg"))); // NOI18N
        add(btnConsultarF, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 170, 50));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/panelForma.jpg"))); // NOI18N
        add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 300));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    public javax.swing.JButton btnConsultarF;
    public javax.swing.JTextField cajaFormaCF;
    private javax.swing.JLabel eLabelCF;
    private javax.swing.JLabel eTuberculoCF;
    public javax.swing.JComboBox<String> jComboBoxPapasCF;
    // End of variables declaration//GEN-END:variables
}
