/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;


/**
 *
 * @author Sara
 */
public class PanelMenu extends javax.swing.JPanel {



    public PanelMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInsertarM = new javax.swing.JButton();
        btnVerM = new javax.swing.JButton();
        btnConsultarM = new javax.swing.JButton();
        btnSalirGeneral = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0,0,0,0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInsertarM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/btninsertar.jpg"))); // NOI18N
        btnInsertarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarMActionPerformed(evt);
            }
        });
        add(btnInsertarM, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 130, 40));

        btnVerM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/verbtn.jpg"))); // NOI18N
        btnVerM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerMActionPerformed(evt);
            }
        });
        add(btnVerM, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 140, 40));

        btnConsultarM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/btnconsultar.jpg"))); // NOI18N
        add(btnConsultarM, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 170, 40));

        btnSalirGeneral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/salirbtn.jpg"))); // NOI18N
        btnSalirGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirGeneralActionPerformed(evt);
            }
        });
        add(btnSalirGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 100, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pmenu.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 370));
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerMActionPerformed

    private void btnInsertarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertarMActionPerformed

    private void btnSalirGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirGeneralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirGeneralActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnConsultarM;
    public javax.swing.JButton btnInsertarM;
    public javax.swing.JButton btnSalirGeneral;
    public javax.swing.JButton btnVerM;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
