/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Sara
 */
public class PanelEspecie extends javax.swing.JPanel {

    /**
     * Creates new form PanelEspecie
     */
    public PanelEspecie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eEspecieCE = new javax.swing.JLabel();
        cajaEspecieCE = new javax.swing.JTextField();
        jComboBoxEspecie = new javax.swing.JComboBox<>();
        eLabelCE = new javax.swing.JLabel();
        btnConsultarEspecie = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eEspecieCE.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        eEspecieCE.setText("Especie");
        add(eEspecieCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));
        add(cajaEspecieCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 200, -1));

        jComboBoxEspecie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBoxEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 190, -1));

        eLabelCE.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        eLabelCE.setText("Papas");
        add(eLabelCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));

        btnConsultarEspecie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/consultarVE.jpg"))); // NOI18N
        btnConsultarEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarEspecieActionPerformed(evt);
            }
        });
        add(btnConsultarEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 170, 50));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/panelEspecie.jpg"))); // NOI18N
        add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 300));
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarEspecieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarEspecieActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    public javax.swing.JButton btnConsultarEspecie;
    public javax.swing.JTextField cajaEspecieCE;
    private javax.swing.JLabel eEspecieCE;
    private javax.swing.JLabel eLabelCE;
    public javax.swing.JComboBox<String> jComboBoxEspecie;
    // End of variables declaration//GEN-END:variables
}
