/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Sara
 */
public class PanelInsertar extends javax.swing.JPanel {

    /**
     * Creates new form PanelInsertar
     */
    public PanelInsertar() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zonas = new javax.swing.ButtonGroup();
        btnInsertarP = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cajaNombre = new javax.swing.JTextField();
        cajaEspecie = new javax.swing.JTextField();
        cajaHabito = new javax.swing.JTextField();
        cajaFloracion = new javax.swing.JTextField();
        cajaBayas = new javax.swing.JTextField();
        cajaTuberculos = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        btnSalirP = new javax.swing.JButton();
        btnLimpiarP = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInsertarP.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/insertarbtn.jpg"))); // NOI18N
        btnInsertarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarPActionPerformed(evt);
            }
        });
        add(btnInsertarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 130, 40));

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 153));
        jLabel1.setText("Zona de Producción");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Insertar datos");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 153));
        jLabel4.setText("Nombre");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 153));
        jLabel3.setText("Especie");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 153));
        jLabel5.setText("Hábito de crecimiento");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 153));
        jLabel6.setText("Floración");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 255, 153));
        jLabel7.setText("Bayas");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 255, 153));
        jLabel8.setText("Tubérculos");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        cajaNombre.setBackground(new java.awt.Color(204, 255, 204));
        cajaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaNombreActionPerformed(evt);
            }
        });
        add(cajaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 200, -1));

        cajaEspecie.setBackground(new java.awt.Color(204, 255, 204));
        add(cajaEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 200, -1));

        cajaHabito.setBackground(new java.awt.Color(204, 255, 204));
        add(cajaHabito, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 200, -1));

        cajaFloracion.setBackground(new java.awt.Color(204, 255, 204));
        add(cajaFloracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 200, -1));

        cajaBayas.setBackground(new java.awt.Color(204, 255, 204));
        add(cajaBayas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 200, -1));

        cajaTuberculos.setBackground(new java.awt.Color(204, 255, 204));
        add(cajaTuberculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 200, -1));

        zonas.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(204, 255, 204));
        jRadioButton2.setText("Nariño");
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, -1));

        zonas.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(204, 255, 204));
        jRadioButton1.setText("Boyacá ");
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, -1, -1));

        zonas.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(204, 255, 204));
        jRadioButton4.setText("Cundinamarca");
        add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, -1, -1));

        btnSalirP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/salir.jpg"))); // NOI18N
        add(btnSalirP, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 90, 40));

        btnLimpiarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/limpiarbtn.jpg"))); // NOI18N
        add(btnLimpiarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 110, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/insertar.jpg"))); // NOI18N
        add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 690, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void cajaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaNombreActionPerformed

    private void btnInsertarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertarPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnInsertarP;
    private javax.swing.JButton btnLimpiarP;
    private javax.swing.JButton btnSalirP;
    private javax.swing.JTextField cajaBayas;
    private javax.swing.JTextField cajaEspecie;
    private javax.swing.JTextField cajaFloracion;
    private javax.swing.JTextField cajaHabito;
    private javax.swing.JTextField cajaNombre;
    private javax.swing.JTextField cajaTuberculos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.ButtonGroup zonas;
    // End of variables declaration//GEN-END:variables
}
